stages:
  - install
  - lint
  - test
  - deploy

test:
  stage: test
  script:
    - echo "No backend tests implemented yet"

image: node:22

install:
  stage: install
  script:
    - npm ci
  artifacts:
    paths:
      - node_modules/

lint:
  stage: lint
  dependencies:
    - install
  script:
    - npm run lint

trigger-deploy:
  stage: deploy

  trigger:
    project: 1dv613/student/sa226jf/workspace/lifeFlow-deploy
    branch: main

  rules:
  - if: '$CI_COMMIT_BRANCH == "main"'
