default:
  artifacts:
    expire_in: 1 day

stages:
  - install
  - lint
  - test
  - build
  - deploy

image: node:22-alpine

cache:
  key:
    files:
      - package-lock.json
  paths:
    - .npm/

install:
  stage: install

  script:
    - npm ci --cache .npm --prefer-offline

  artifacts:
    paths:
      - node_modules/

lint:
  stage: lint

  dependencies:
    - install

  script:
    - npm run lint

test:
  stage: test

  dependencies:
    - install

  variables:
    NODE_ENV: test

  script:
    - echo "No backend tests implemented yet"

build-image:
  stage: build

  image:
    name: gcr.io/kaniko-project/executor:v1.23.1-debug
    entrypoint: [""]

  script:
    - mkdir -p /kaniko/.docker

    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json

    - >
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --target production
      --cache=true
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}"

  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

trigger-deploy:
  stage: deploy

  needs:
    - lint
    - test
    - build-image

  trigger:
    project: 1dv613/student/sa226jf/workspace/lifeflow-deploy
    branch: main
    strategy: depend

  variables:
    IMAGE_TAG: $CI_COMMIT_SHA

  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
