import mongoose from 'mongoose'

/**
 * Notification subscription model.
 *
 * Stores a user's Web Push subscription information
 * used for sending push notifications to a specific device.
 */
const notificationSubscriptionSchema =
  new mongoose.Schema(
    {
      /**
       * User that owns the subscription.
       */
      user: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        required: true,
      },

      /**
       * Unique push endpoint generated by the browser.
       */
      endpoint: {
        type: String,
        required: true,
      },

      /**
       * Web Push encryption keys.
       */
      keys: {
        /**
         * Public encryption key.
         */
        p256dh: String,

        /**
         * Authentication secret.
         */
        auth: String,
      },
    },
    {
      timestamps: true,
    },
  )

notificationSubscriptionSchema.index(
  { endpoint: 1 },
  { unique: true },
)

export default mongoose.model(
  'NotificationSubscription',
  notificationSubscriptionSchema,
)
